language: "ko"
early_access: false
enable_free_tier: true

reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  poem: false
  review_status: true
  collapse_walkthrough: true
  auto_title_placeholder: "@coderabbitai"

  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT REVIEW"
    drafts: false
    base_branches:
      - "main"

  tools:
    shellcheck:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout: 5

  path_filters:
    - "!**/build/**"
    - "!**/out/**"
    - "!**/.gradle/**"
    - "!**/gradle/**"
    - "!**/gradlew"
    - "!**/gradlew.bat"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.gif"
    - "!**/*.svg"
    - "!**/package-lock.json"
    - "!**/yarn.lock"

  # 모듈별 리뷰 가이드 (reviews 섹션 내부로 이동)
  path_instructions:
    - path: "gateway/**"
      instructions: |
        이것은 API Gateway 모듈입니다.
        - Spring Cloud Gateway 패턴을 따르는지 확인하세요.
        - 라우팅 설정이 올바른지 검토하세요.
        - JWT 토큰 검증 로직을 주의깊게 확인하세요.

chat:
  auto_reply: true